### ISSUE TITLE
Migrate to using Xenial in Travis

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#5001]
Write a codemod that updates the `.travis.yml` file to include:

```yml
dist: xenial
services:
 - xvfb
```

This can replace:

```yml
dist: trusty
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
```

The codemod should probably:

- Look for `dist`; if it’s there, update it to `xenial`, otherwise add it
- Look for these lines together and remove them:

```yml
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
```

We’ll need to check the diff for each PR just to make sure other `before_install` scripts still work.
